package cn.zno.smse.dao;

import cn.zno.smse.pojo.SystemRoleMenuLink;
import cn.zno.smse.pojo.SystemRoleMenuLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRoleMenuLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int countByExample(SystemRoleMenuLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRoleMenuLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int insert(SystemRoleMenuLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleMenuLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    List<SystemRoleMenuLink> selectByExample(SystemRoleMenuLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoleMenuLink record, @Param("example") SystemRoleMenuLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_ROLE_MENU_LINK
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoleMenuLink record, @Param("example") SystemRoleMenuLinkExample example);
}