package cn.zno.smse.dao;

import cn.zno.smse.pojo.SystemUserRoleLink;
import cn.zno.smse.pojo.SystemUserRoleLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemUserRoleLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int countByExample(SystemUserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int deleteByExample(SystemUserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int insert(SystemUserRoleLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int insertSelective(SystemUserRoleLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    List<SystemUserRoleLink> selectByExample(SystemUserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemUserRoleLink record, @Param("example") SystemUserRoleLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSE_USER_ROLE_LINK
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemUserRoleLink record, @Param("example") SystemUserRoleLinkExample example);
}