package cn.zno.smse.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Person {
	
	
	private Date start;
	private Date end;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.AGE
     *
     * @mbggenerated
     */
    private BigDecimal age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_PERSON.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.ID
     *
     * @return the value of SMSE_PERSON.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.ID
     *
     * @param id the value for SMSE_PERSON.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.NAME
     *
     * @return the value of SMSE_PERSON.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.NAME
     *
     * @param name the value for SMSE_PERSON.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.AGE
     *
     * @return the value of SMSE_PERSON.AGE
     *
     * @mbggenerated
     */
    public BigDecimal getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.AGE
     *
     * @param age the value for SMSE_PERSON.AGE
     *
     * @mbggenerated
     */
    public void setAge(BigDecimal age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.BIRTHDAY
     *
     * @return the value of SMSE_PERSON.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.BIRTHDAY
     *
     * @param birthday the value for SMSE_PERSON.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.TYPE
     *
     * @return the value of SMSE_PERSON.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.TYPE
     *
     * @param type the value for SMSE_PERSON.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_PERSON.SEX
     *
     * @return the value of SMSE_PERSON.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_PERSON.SEX
     *
     * @param sex the value for SMSE_PERSON.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

	public Date getStart() {
		return start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}
}