package cn.zno.smse.pojo;

import java.io.Serializable;

public class SystemUserRoleLink implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_USER_ROLE_LINK.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_USER_ROLE_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_USER_ROLE_LINK.USER_ID
     *
     * @return the value of SMSE_USER_ROLE_LINK.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_USER_ROLE_LINK.USER_ID
     *
     * @param userId the value for SMSE_USER_ROLE_LINK.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_USER_ROLE_LINK.ROLE_ID
     *
     * @return the value of SMSE_USER_ROLE_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_USER_ROLE_LINK.ROLE_ID
     *
     * @param roleId the value for SMSE_USER_ROLE_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}