package cn.zno.smse.pojo;

public class SystemAccessPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ACCESS_PERMISSION.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ACCESS_PERMISSION.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ACCESS_PERMISSION.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ACCESS_PERMISSION.MENU_ID
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ACCESS_PERMISSION.ID
     *
     * @return the value of SMSE_ACCESS_PERMISSION.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ACCESS_PERMISSION.ID
     *
     * @param id the value for SMSE_ACCESS_PERMISSION.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ACCESS_PERMISSION.NAME
     *
     * @return the value of SMSE_ACCESS_PERMISSION.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ACCESS_PERMISSION.NAME
     *
     * @param name the value for SMSE_ACCESS_PERMISSION.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ACCESS_PERMISSION.URL
     *
     * @return the value of SMSE_ACCESS_PERMISSION.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ACCESS_PERMISSION.URL
     *
     * @param url the value for SMSE_ACCESS_PERMISSION.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ACCESS_PERMISSION.MENU_ID
     *
     * @return the value of SMSE_ACCESS_PERMISSION.MENU_ID
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ACCESS_PERMISSION.MENU_ID
     *
     * @param menuId the value for SMSE_ACCESS_PERMISSION.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}