package cn.zno.smse.pojo;

import java.io.Serializable;

public class SystemRoleMenuLink implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ROLE_MENU_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMSE_ROLE_MENU_LINK.MENU_ID
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ROLE_MENU_LINK.ROLE_ID
     *
     * @return the value of SMSE_ROLE_MENU_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ROLE_MENU_LINK.ROLE_ID
     *
     * @param roleId the value for SMSE_ROLE_MENU_LINK.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMSE_ROLE_MENU_LINK.MENU_ID
     *
     * @return the value of SMSE_ROLE_MENU_LINK.MENU_ID
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMSE_ROLE_MENU_LINK.MENU_ID
     *
     * @param menuId the value for SMSE_ROLE_MENU_LINK.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}